/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: 9e63ff177cbb26fe3b96c0e44a54a2d2)
interface __BaseEnv_Env {
	DB: D1Database;
	ALLOWED_ORIGINS: "https://romantamrazov.github.io,http://localhost:5173,http://127.0.0.1:5173";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS">> {}
}
