import assert from 'node:assert/strict'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { pathToFileURL, fileURLToPath } from 'node:url'
import { resolve } from 'node:path'
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE_PATH ? pathToFileURL(process.env.PLAYWRIGHT_MODULE_PATH).href : 'playwright')
const root = fileURLToPath(new URL('../', import.meta.url)), qa = resolve(root, 'qa')
await mkdir(qa, { recursive: true })
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true })
const context = await browser.newContext({ viewport: { width: 1440, height: 1050 }, acceptDownloads: true })
const page = await context.newPage(), errors = []
page.on('pageerror', error => errors.push(error.message))
await context.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort())
await page.goto('http://127.0.0.1:8765')
await page.screenshot({ path: resolve(qa, 'home-desktop.png'), fullPage: true })
await page.getByLabel('Предмет закупки, ИНН поставщика или ОКПД2').fill('ИНН 7801314509')
await page.getByLabel('Бюджет закупки, ₽', { exact: true }).fill('450000')
await page.getByRole('button', { name: 'Найти поставщиков', exact: true }).click()
await page.locator('.supplier-card').first().waitFor()
assert.ok(await page.locator('a[href="tel:+78127140614"]').count())
await page.locator('.save-button').first().click()
await page.screenshot({ path: resolve(qa, 'supplier-contacts.png'), fullPage: true })
await page.getByLabel('Предмет закупки, ИНН поставщика или ОКПД2').fill('медицинские перчатки')
await page.getByRole('button', { name: 'Найти поставщиков', exact: true }).click()
await page.locator('.supplier-card').first().waitFor()
const secondSupplier = await page.locator('.supplier-name').nth(1).innerText()
await page.locator('.supplier-card .card-description').nth(1).scrollIntoViewIfNeeded()
const description = await page.locator('.supplier-card .card-description').nth(1).boundingBox()
assert.ok(description)
await page.mouse.click(description.x + description.width / 2, description.y + description.height / 2)
assert.equal(await page.locator('.supplier-detail h2').innerText(), secondSupplier)
await page.locator('.supplier-detail .history-trail summary').click()
assert.ok(await page.locator('.supplier-detail .history-trail-body').innerText())
const checkboxes = page.locator('.compare-check input')
await checkboxes.nth(0).check(); await checkboxes.nth(1).check()
await page.getByRole('button', { name: 'Сравнить компании', exact: true }).click()
assert.equal(await page.locator('dialog').evaluate(node => node.open), true)
await page.screenshot({ path: resolve(qa, 'compare.png'), fullPage: true })
await page.getByRole('button', { name: 'Закрыть сравнение', exact: true }).click()
await page.getByRole('button', { name: 'Очистить сравнение', exact: true }).click()
await page.getByRole('button', { name: 'Список закупок CSV', exact: true }).click()
await page.getByLabel('Загрузить CSV').setInputFiles(resolve(root, 'input_samples/test/purchases_2.csv'))
await page.getByRole('button', { name: 'Открыть лот 5968880', exact: true }).waitFor()
assert.equal(await page.locator('.lot-select').count(), 38)
assert.equal(await page.locator('.provisional-note').count(), 1)
assert.ok((await page.locator('.upload-hint').innerText()).includes('Лоты собраны по ТРУ'))
await page.getByLabel('Загрузить CSV').setInputFiles(resolve(root, 'input_samples/test/purchases_1.csv'))
await page.getByRole('button', { name: 'Открыть лот 5968880', exact: true }).waitFor()
assert.equal(await page.locator('.lot-select').count(), 38)
assert.equal(await page.locator('.provisional-note').count(), 0)
assert.equal(await page.locator('.staged-files li').count(), 2)
assert.ok((await page.locator('.bulk-stats').innerText()).includes('670'))
await page.getByRole('button', { name: 'Подобрать для этого лота', exact: true }).click()
await page.getByRole('button', { name: 'Обновить подбор', exact: true }).waitFor()
const firstInn = await page.locator('.lot-candidates').innerText()
assert.ok(firstInn.includes('ИНН') || await page.locator('.lot-no-results').innerText())
assert.equal(await page.locator('.lot-meta .customer-links a').count(), 2)
if (await page.locator('.lot-candidates .candidate-open').count()) {
  await page.locator('.lot-candidates .candidate-open').first().click()
  assert.equal(await page.locator('.lot-candidates .candidate-expanded').count(), 1)
  await page.locator('.lot-candidates .history-trail summary').first().click()
  assert.ok(await page.locator('.lot-candidates .history-trail-body').first().innerText())
}
await page.getByRole('button', { name: 'Следующий лот', exact: true }).click()
await page.getByRole('button', { name: 'Предыдущий лот', exact: true }).click()
assert.equal(await page.locator('.lot-candidates').innerText(), firstInn)
await page.screenshot({ path: resolve(qa, 'lots-test-desktop.png'), fullPage: true })
await page.getByLabel('Поиск по lot_id или предмету').fill('5968880')
assert.equal(await page.locator('.lot-select').count(), 1)
await page.getByLabel('Поиск по lot_id или предмету').fill('')
await page.getByRole('button', { name: 'Получить рекомендации', exact: true }).click()
await page.getByRole('button', { name: 'Скачать CSV', exact: true }).waitFor({ state: 'visible' })
await page.waitForFunction(() => !document.querySelector('.bulk-controls .button.primary')?.textContent?.includes('Подбираем'))
assert.equal(await page.locator('.lot-dot.pending').count(), 0)
assert.equal(await page.locator('.lot-dot.error').count(), 0)
const download = page.waitForEvent('download')
await page.getByRole('button', { name: 'Скачать CSV', exact: true }).click()
await (await download).saveAs(resolve(qa, 'test-recommendations.csv'))
await page.getByRole('button', { name: 'Очистить набор', exact: true }).click()
await page.locator('.lot-select').first().waitFor({ state: 'detached' })
for (let i = 1; i <= 8; i++) {
  await page.getByLabel('Загрузить CSV').setInputFiles(resolve(root, 'input_samples/final/purchases_' + i + '.csv'))
  await page.waitForFunction(expected => document.querySelectorAll('.staged-files li').length === expected &&
    !document.querySelector('input[aria-label="Загрузить CSV"]')?.disabled, i)
}
await page.getByRole('button', { name: 'Открыть лот 6041774', exact: true }).waitFor()
assert.equal(await page.locator('.lot-select').count(), 99)
assert.equal(await page.locator('.staged-files li').count(), 8)
assert.ok((await page.locator('.lot-detail').innerText()).includes('7813131108'))
await page.getByRole('button', { name: 'Убрать файл purchases_8.csv', exact: true }).click()
await page.waitForFunction(() => document.querySelector('.upload-summary')?.textContent?.includes('1100 позиций ТРУ'))
await page.getByLabel('Загрузить CSV').setInputFiles(resolve(root, 'input_samples/final/purchases_8.csv'))
await page.waitForFunction(() => document.querySelector('.upload-summary')?.textContent?.includes('1468 позиций ТРУ'))
assert.ok((await page.locator('.import-warnings').innerText()).includes('восстановлены'))
await page.getByRole('button', { name: 'Подобрать для этого лота', exact: true }).click()
await page.getByRole('button', { name: 'Обновить подбор', exact: true }).waitFor()
await page.screenshot({ path: resolve(qa, 'lots-final-desktop.png'), fullPage: true })
await page.getByRole('button', { name: 'Получить рекомендации', exact: true }).click()
await page.waitForFunction(() => !document.querySelector('.bulk-controls .button.primary')?.textContent?.includes('Подбираем'), null, { timeout: 120000 })
assert.equal(await page.locator('.lot-dot.pending').count(), 0)
assert.equal(await page.locator('.lot-dot.error').count(), 0)
const finalDownload = page.waitForEvent('download')
await page.getByRole('button', { name: 'Скачать CSV', exact: true }).click()
await (await finalDownload).saveAs(resolve(qa, 'final-recommendations.csv'))
await page.waitForFunction(() => {
  const rows = JSON.parse(sessionStorage.getItem('rltttsk-lots-session-v1') || '{}').rows
  return rows?.length === 99 && rows.every(row => ['done', 'empty', 'error'].includes(row.status))
})
await page.reload()
await page.getByRole('button', { name: 'Список закупок CSV', exact: true }).click()
assert.equal(await page.locator('.lot-select').count(), 99)
assert.equal(await page.locator('.lot-dot.pending').count(), 0)
assert.equal(await page.locator('.lot-dot.cancelled').count(), 0)
await page.setViewportSize({ width: 390, height: 844 })
await page.getByLabel('Поиск по lot_id или предмету').fill('6041774')
await page.locator('.lot-browser').scrollIntoViewIfNeeded()
await page.screenshot({ path: resolve(qa, 'lots-mobile.png') })
await page.locator('.lot-detail').scrollIntoViewIfNeeded()
await page.screenshot({ path: resolve(qa, 'lot-detail-mobile.png') })
const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1)
assert.equal(overflow, false)
assert.deepEqual(errors, [])
await writeFile(resolve(qa, 'browser-report.json'), JSON.stringify({ testLots: 38, testItems: 670, finalLots: 99, finalItems: 1468,
  truOnlyProvisionalLots: true, sequentialCsvSelection: true, removeAndReaddCsv: true,
  contactsClickable: true, supplierCardClickable: true, customerLinks: true, historyExpanded: true, comparison: true, lotNavigationKeepsResults: true,
  resultsSurviveReload: true, allFinalLotsProcessed: true, csvDownload: true, mobileOverflow: false, pageErrors: errors }, null, 2))
await browser.close()
console.log('Browser checks passed: contacts, comparison, real CSV import, lot navigation, export, mobile.')
